import { Material } from "@/types";

// Initial materials based on your list
export const initialMaterials: Omit<Material, "id" | "lastUpdated">[] = [
  // CHINT MCB BREAKERS
  { category: "CHINT MCB", name: "6A", variant: "s.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "CHINT MCB", name: "6A", variant: "d.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "CHINT MCB", name: "6A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "CHINT MCB", name: "10A", variant: "s.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "CHINT MCB", name: "10A", variant: "d.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "CHINT MCB", name: "10A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "CHINT MCB", name: "16A", variant: "s.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "CHINT MCB", name: "16A", variant: "d.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "CHINT MCB", name: "16A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "CHINT MCB", name: "20A", variant: "s.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "CHINT MCB", name: "20A", variant: "d.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "CHINT MCB", name: "20A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "CHINT MCB", name: "25A", variant: "s.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "CHINT MCB", name: "25A", variant: "d.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "CHINT MCB", name: "25A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "CHINT MCB", name: "32A", variant: "s.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "CHINT MCB", name: "32A", variant: "d.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "CHINT MCB", name: "32A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "CHINT MCB", name: "40A", variant: "s.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "CHINT MCB", name: "40A", variant: "d.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "CHINT MCB", name: "40A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "CHINT MCB", name: "63A", variant: "s.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "CHINT MCB", name: "63A", variant: "d.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "CHINT MCB", name: "63A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "CHINT MCB", name: "80A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "CHINT MCB", name: "100A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "CHINT MCB", name: "125A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },

  // CHINT Isolators
  { category: "CHINT Isolator", name: "63A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "CHINT Isolator", name: "80A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "CHINT Isolator", name: "100A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "CHINT Isolator", name: "125A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },

  // CHINT Earth Leakages
  { category: "CHINT Earth Leakage", name: "25A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "CHINT Earth Leakage", name: "63A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },

  // CHINT MCCB BREAKERS
  { category: "CHINT MCCB", name: "100A", variant: undefined, quantity: 0, minThreshold: 3, unit: "pcs" },
  { category: "CHINT MCCB", name: "125A", variant: undefined, quantity: 0, minThreshold: 3, unit: "pcs" },
  { category: "CHINT MCCB", name: "150A", variant: undefined, quantity: 0, minThreshold: 3, unit: "pcs" },
  { category: "CHINT MCCB", name: "160A", variant: undefined, quantity: 0, minThreshold: 3, unit: "pcs" },
  { category: "CHINT MCCB", name: "175A", variant: undefined, quantity: 0, minThreshold: 3, unit: "pcs" },
  { category: "CHINT MCCB", name: "200A", variant: undefined, quantity: 0, minThreshold: 3, unit: "pcs" },
  { category: "CHINT MCCB", name: "225A", variant: undefined, quantity: 0, minThreshold: 3, unit: "pcs" },
  { category: "CHINT MCCB", name: "250A", variant: undefined, quantity: 0, minThreshold: 3, unit: "pcs" },
  { category: "CHINT MCCB", name: "300A", variant: undefined, quantity: 0, minThreshold: 3, unit: "pcs" },
  { category: "CHINT MCCB", name: "315A", variant: undefined, quantity: 0, minThreshold: 3, unit: "pcs" },
  { category: "CHINT MCCB", name: "350A", variant: undefined, quantity: 0, minThreshold: 3, unit: "pcs" },
  { category: "CHINT MCCB", name: "400A", variant: undefined, quantity: 0, minThreshold: 3, unit: "pcs" },
  { category: "CHINT MCCB", name: "500A", variant: undefined, quantity: 0, minThreshold: 2, unit: "pcs" },
  { category: "CHINT MCCB", name: "600A", variant: undefined, quantity: 0, minThreshold: 2, unit: "pcs" },
  { category: "CHINT MCCB", name: "630A", variant: undefined, quantity: 0, minThreshold: 2, unit: "pcs" },
  { category: "CHINT MCCB", name: "800A", variant: undefined, quantity: 0, minThreshold: 2, unit: "pcs" },
  { category: "CHINT MCCB", name: "1200A", variant: undefined, quantity: 0, minThreshold: 1, unit: "pcs" },
  { category: "CHINT MCCB", name: "1600A", variant: undefined, quantity: 0, minThreshold: 1, unit: "pcs" },

  // LS MCB BREAKERS
  { category: "LS MCB", name: "63A", variant: "s.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "LS MCB", name: "63A", variant: "d.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "LS MCB", name: "63A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },

  // MITSUBISHI MCCB BREAKERS
  { category: "MITSUBISHI MCCB", name: "30A", variant: undefined, quantity: 0, minThreshold: 3, unit: "pcs" },
  { category: "MITSUBISHI MCCB", name: "100A", variant: undefined, quantity: 0, minThreshold: 3, unit: "pcs" },
  { category: "MITSUBISHI MCCB", name: "160A", variant: undefined, quantity: 0, minThreshold: 3, unit: "pcs" },
  { category: "MITSUBISHI MCCB", name: "175A", variant: undefined, quantity: 0, minThreshold: 3, unit: "pcs" },
  { category: "MITSUBISHI MCCB", name: "200A", variant: undefined, quantity: 0, minThreshold: 3, unit: "pcs" },
  { category: "MITSUBISHI MCCB", name: "225A", variant: undefined, quantity: 0, minThreshold: 3, unit: "pcs" },
  { category: "MITSUBISHI MCCB", name: "250A", variant: undefined, quantity: 0, minThreshold: 3, unit: "pcs" },
  { category: "MITSUBISHI MCCB", name: "300A", variant: undefined, quantity: 0, minThreshold: 3, unit: "pcs" },
  { category: "MITSUBISHI MCCB", name: "350A", variant: undefined, quantity: 0, minThreshold: 2, unit: "pcs" },
  { category: "MITSUBISHI MCCB", name: "400A", variant: undefined, quantity: 0, minThreshold: 2, unit: "pcs" },
  { category: "MITSUBISHI MCCB", name: "500A", variant: undefined, quantity: 0, minThreshold: 2, unit: "pcs" },
  { category: "MITSUBISHI MCCB", name: "600A", variant: undefined, quantity: 0, minThreshold: 2, unit: "pcs" },
  { category: "MITSUBISHI MCCB", name: "800A", variant: undefined, quantity: 0, minThreshold: 1, unit: "pcs" },

  // SCHNEIDER MCB BREAKERS
  { category: "SCHNEIDER MCB", name: "2A", variant: "s.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "2A", variant: "d.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "2A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "4A", variant: "s.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "4A", variant: "d.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "4A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "6A", variant: "s.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "6A", variant: "d.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "6A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "10A", variant: "s.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "10A", variant: "d.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "10A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "16A", variant: "s.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "16A", variant: "d.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "16A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "20A", variant: "s.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "20A", variant: "d.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "20A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "25A", variant: "s.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "25A", variant: "d.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "25A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "30A", variant: "s.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "30A", variant: "d.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "30A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "32A", variant: "s.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "32A", variant: "d.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "32A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "40A", variant: "s.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "40A", variant: "d.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "40A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "50A", variant: "s.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "50A", variant: "d.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "50A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "63A", variant: "s.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "63A", variant: "d.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "63A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "80A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },
  { category: "SCHNEIDER MCB", name: "100A", variant: "T.p", quantity: 0, minThreshold: 5, unit: "pcs" },

  // SCHNEIDER MCCB BREAKERS
  { category: "SCHNEIDER MCCB", name: "100A", variant: undefined, quantity: 0, minThreshold: 3, unit: "pcs" },
  { category: "SCHNEIDER MCCB", name: "160A", variant: undefined, quantity: 0, minThreshold: 3, unit: "pcs" },
  { category: "SCHNEIDER MCCB", name: "175A", variant: undefined, quantity: 0, minThreshold: 3, unit: "pcs" },
  { category: "SCHNEIDER MCCB", name: "200A", variant: undefined, quantity: 0, minThreshold: 3, unit: "pcs" },
  { category: "SCHNEIDER MCCB", name: "250A", variant: undefined, quantity: 0, minThreshold: 3, unit: "pcs" },
  { category: "SCHNEIDER MCCB", name: "300A", variant: undefined, quantity: 0, minThreshold: 3, unit: "pcs" },
  { category: "SCHNEIDER MCCB", name: "400A", variant: undefined, quantity: 0, minThreshold: 2, unit: "pcs" },
  { category: "SCHNEIDER MCCB", name: "630A", variant: undefined, quantity: 0, minThreshold: 2, unit: "pcs" },
  { category: "SCHNEIDER MCCB", name: "800A", variant: undefined, quantity: 0, minThreshold: 1, unit: "pcs" },
  { category: "SCHNEIDER MCCB", name: "1600A", variant: undefined, quantity: 0, minThreshold: 1, unit: "pcs" },

  // SCHNEIDER ISOLATOR
  { category: "SCHNEIDER Isolator", name: "160A", variant: undefined, quantity: 0, minThreshold: 3, unit: "pcs" },
  { category: "SCHNEIDER Isolator", name: "400A", variant: undefined, quantity: 0, minThreshold: 2, unit: "pcs" },

  // Continue with other brands... (abbreviated for space - would include all brands from your list)
  
  // Paint categories
  { category: "Paint", name: "Pastel Light", variant: undefined, quantity: 0, minThreshold: 2, unit: "liters" },
  { category: "Paint", name: "Pastel Grey", variant: undefined, quantity: 0, minThreshold: 2, unit: "liters" },
  { category: "Paint", name: "Hammertone", variant: undefined, quantity: 0, minThreshold: 2, unit: "liters" },
  { category: "Paint", name: "Orange Ferrotex", variant: undefined, quantity: 0, minThreshold: 2, unit: "liters" },
  { category: "Paint", name: "Orange Plain", variant: undefined, quantity: 0, minThreshold: 2, unit: "liters" },
  { category: "Paint", name: "Blue Ferrotex", variant: undefined, quantity: 0, minThreshold: 2, unit: "liters" },
  { category: "Paint", name: "Dark Blue", variant: undefined, quantity: 0, minThreshold: 2, unit: "liters" },
  { category: "Paint", name: "Light Blue", variant: undefined, quantity: 0, minThreshold: 2, unit: "liters" },
  { category: "Paint", name: "Plain Blue", variant: undefined, quantity: 0, minThreshold: 2, unit: "liters" },
  { category: "Paint", name: "Steel Blue", variant: undefined, quantity: 0, minThreshold: 2, unit: "liters" },
  { category: "Paint", name: "Charcoal Blue", variant: undefined, quantity: 0, minThreshold: 2, unit: "liters" },
  { category: "Paint", name: "Black Ferrotex", variant: undefined, quantity: 0, minThreshold: 2, unit: "liters" },
  { category: "Paint", name: "Black Gross", variant: undefined, quantity: 0, minThreshold: 2, unit: "liters" },
  { category: "Paint", name: "White Ferrotex", variant: undefined, quantity: 0, minThreshold: 2, unit: "liters" },
  { category: "Paint", name: "White Blue", variant: undefined, quantity: 0, minThreshold: 2, unit: "liters" },
  { category: "Paint", name: "Moss Green", variant: undefined, quantity: 0, minThreshold: 2, unit: "liters" },
  { category: "Paint", name: "Telecom Green", variant: undefined, quantity: 0, minThreshold: 2, unit: "liters" },
  { category: "Paint", name: "Gold", variant: undefined, quantity: 0, minThreshold: 2, unit: "liters" },
  { category: "Paint", name: "Veined Copper", variant: undefined, quantity: 0, minThreshold: 2, unit: "liters" },
  { category: "Paint", name: "Silver", variant: undefined, quantity: 0, minThreshold: 2, unit: "liters" },
  { category: "Paint", name: "Satin Red Traffic", variant: undefined, quantity: 0, minThreshold: 2, unit: "liters" },
  { category: "Paint", name: "Brown Bronze", variant: undefined, quantity: 0, minThreshold: 2, unit: "liters" },
  { category: "Paint", name: "Cream", variant: undefined, quantity: 0, minThreshold: 2, unit: "liters" },
  { category: "Paint", name: "Indigo", variant: undefined, quantity: 0, minThreshold: 2, unit: "liters" },
  { category: "Paint", name: "Yellow", variant: undefined, quantity: 0, minThreshold: 2, unit: "liters" },
  { category: "Paint", name: "Greenish Blue", variant: undefined, quantity: 0, minThreshold: 2, unit: "liters" },

  // Accessories
  { category: "Accessories", name: "Masking Tape", variant: undefined, quantity: 0, minThreshold: 10, unit: "rolls" },
  { category: "Accessories", name: "Degreaser", variant: undefined, quantity: 0, minThreshold: 5, unit: "liters" },
  { category: "Accessories", name: "Thinners", variant: undefined, quantity: 0, minThreshold: 5, unit: "liters" },

  // Terminal Blocks
  { category: "Terminal Block", name: "4mm", variant: undefined, quantity: 0, minThreshold: 20, unit: "pcs" },
  { category: "Terminal Block", name: "6mm", variant: undefined, quantity: 0, minThreshold: 20, unit: "pcs" },
  { category: "Terminal Block", name: "10mm", variant: undefined, quantity: 0, minThreshold: 15, unit: "pcs" },
  { category: "Terminal Block", name: "16mm", variant: undefined, quantity: 0, minThreshold: 15, unit: "pcs" },
  { category: "Terminal Block", name: "35mm", variant: undefined, quantity: 0, minThreshold: 10, unit: "pcs" },
];