// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bugxvelaswsqgbpazvxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1Z3h2ZWxhc3dzcWdicGF6dnhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg4MTIxNDcsImV4cCI6MjA4NDM4ODE0N30.tlsL4SSnrOdRMG8Atcc6i_xeW_scZgHiI6ZIF8ToMDs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
